/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "api.apartment.index": [],
    "api.apartment.store": [],
    "api.apartment.show": [
        {
            "name": "apartment",
            "required": true
        }
    ],
    "api.apartment.update": [
        {
            "name": "apartment",
            "required": true
        }
    ],
    "api.apartment.destroy": [
        {
            "name": "apartment",
            "required": true
        }
    ],
    "units.index": [],
    "units.create": [],
    "units.store": [],
    "units.edit": [
        {
            "name": "unit",
            "required": true,
            "binding": "id"
        }
    ],
    "units.update": [
        {
            "name": "unit",
            "required": true,
            "binding": "id"
        }
    ],
    "units.destroy": [
        {
            "name": "unit",
            "required": true,
            "binding": "id"
        }
    ],
    "residents.index": [],
    "residents.create": [],
    "residents.store": [],
    "residents.edit": [
        {
            "name": "resident",
            "required": true,
            "binding": "id"
        }
    ],
    "residents.update": [
        {
            "name": "resident",
            "required": true,
            "binding": "id"
        }
    ],
    "residents.destroy": [
        {
            "name": "resident",
            "required": true,
            "binding": "id"
        }
    ],
    "maintenance-slabs.index": [],
    "maintenance-slabs.create": [],
    "maintenance-slabs.store": [],
    "maintenance-slabs.edit": [
        {
            "name": "maintenance_slab",
            "required": true
        }
    ],
    "maintenance-slabs.update": [
        {
            "name": "maintenance_slab",
            "required": true
        }
    ],
    "maintenance-slabs.destroy": [
        {
            "name": "maintenance_slab",
            "required": true
        }
    ],
    "api.billing.index": [],
    "api.billing.store": [],
    "api.billing.show": [
        {
            "name": "billing",
            "required": true
        }
    ],
    "api.billing.update": [
        {
            "name": "billing",
            "required": true
        }
    ],
    "api.billing.destroy": [
        {
            "name": "billing",
            "required": true
        }
    ],
    "charges.index": [],
    "charges.create": [],
    "charges.store": [],
    "charges.edit": [
        {
            "name": "charge",
            "required": true,
            "binding": "id"
        }
    ],
    "charges.update": [
        {
            "name": "charge",
            "required": true,
            "binding": "id"
        }
    ],
    "charges.destroy": [
        {
            "name": "charge",
            "required": true,
            "binding": "id"
        }
    ],
    "payments.index": [],
    "payments.create": [],
    "payments.store": [],
    "payments.edit": [
        {
            "name": "payment",
            "required": true,
            "binding": "id"
        }
    ],
    "payments.update": [
        {
            "name": "payment",
            "required": true,
            "binding": "id"
        }
    ],
    "payments.destroy": [
        {
            "name": "payment",
            "required": true,
            "binding": "id"
        }
    ],
    "expenses.index": [],
    "expenses.create": [],
    "expenses.store": [],
    "expenses.edit": [
        {
            "name": "expense",
            "required": true,
            "binding": "id"
        }
    ],
    "expenses.update": [
        {
            "name": "expense",
            "required": true,
            "binding": "id"
        }
    ],
    "expenses.destroy": [
        {
            "name": "expense",
            "required": true,
            "binding": "id"
        }
    ],
    "charges.generate": [],
    "charges.generate.store": [],
    "api.import.index": [],
    "api.import.store": [],
    "api.import.show": [
        {
            "name": "import",
            "required": true
        }
    ],
    "api.import.update": [
        {
            "name": "import",
            "required": true
        }
    ],
    "api.import.destroy": [
        {
            "name": "import",
            "required": true
        }
    ],
    "uploads.index": [],
    "uploads.create": [],
    "uploads.store": [],
    "uploads.destroy": [
        {
            "name": "upload",
            "required": true,
            "binding": "id"
        }
    ],
    "uploads.retry": [
        {
            "name": "upload",
            "required": true,
            "binding": "id"
        }
    ],
    "review-queue.index": [],
    "review-queue.assign-payment": [
        {
            "name": "parsedTransaction",
            "required": true,
            "binding": "id"
        }
    ],
    "review-queue.assign-expense": [
        {
            "name": "parsedTransaction",
            "required": true,
            "binding": "id"
        }
    ],
    "review-queue.dismiss": [
        {
            "name": "parsedTransaction",
            "required": true,
            "binding": "id"
        }
    ],
    "api.sheet.index": [],
    "api.sheet.store": [],
    "api.sheet.show": [
        {
            "name": "sheet",
            "required": true
        }
    ],
    "api.sheet.update": [
        {
            "name": "sheet",
            "required": true
        }
    ],
    "api.sheet.destroy": [
        {
            "name": "sheet",
            "required": true
        }
    ],
    "sheet.index": [],
    "sheet.create": [],
    "sheet.store": [],
    "sheet.show": [
        {
            "name": "sheet",
            "required": true
        }
    ],
    "sheet.edit": [
        {
            "name": "sheet",
            "required": true
        }
    ],
    "sheet.update": [
        {
            "name": "sheet",
            "required": true
        }
    ],
    "sheet.destroy": [
        {
            "name": "sheet",
            "required": true
        }
    ],
    "telegram.webhook": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
